# netlify.toml
# This file tells Netlify how to build and deploy your site

[build]
  # Directory to publish and build command
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false"

# Redirect all URLs to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for caching and security
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"